# Generated by Django 2.2.1 on 2019-05-23 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.AutoField(primary_key=True, serialize=False)),
                ('contract_dt', models.DateField()),
            ],
            options={
                'db_table': 'contract',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContractOverviewByPerson',
            fields=[
                ('contract_id', models.IntegerField()),
                ('contract_dt', models.DateField()),
                ('document_series', models.CharField(blank=True, max_length=10, null=True)),
                ('document_no', models.IntegerField()),
                ('person_surname_txt', models.CharField(max_length=50)),
                ('person_name_txt', models.CharField(max_length=50)),
                ('person_father_name_txt', models.CharField(blank=True, max_length=50, null=True)),
                ('connection_type_txt', models.CharField(max_length=50)),
                ('sphere_txt', models.CharField(blank=True, max_length=100, null=True)),
                ('name_txt', models.CharField(max_length=100)),
                ('number_of_payments', models.BigIntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContractPayment',
            fields=[
                ('contract_payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_dt', models.DateField()),
                ('payment_amt', models.IntegerField()),
                ('contract_payment_type', models.CharField(max_length=1)),
                ('contract_payment_cash_voucher_no', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'contract_payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('sphere_txt', models.CharField(blank=True, max_length=100, null=True)),
                ('direction', models.CharField(blank=True, max_length=1, null=True)),
                ('name_txt', models.CharField(max_length=100)),
                ('price_per_hour', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('number_of_hours', models.SmallIntegerField()),
                ('course_start_dt', models.DateField()),
                ('course_end_dt', models.DateField()),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseClass',
            fields=[
                ('course_class_id', models.AutoField(primary_key=True, serialize=False)),
                ('week_day_txt', models.CharField(max_length=1)),
                ('start_tm', models.TimeField()),
                ('end_tm', models.TimeField()),
            ],
            options={
                'db_table': 'course_class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseElement',
            fields=[
                ('course_element_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'course_element',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('birth_dt', models.DateField()),
                ('inn_no', models.CharField(max_length=12, unique=True)),
            ],
            options={
                'db_table': 'person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonDocument',
            fields=[
                ('person_document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_no', models.IntegerField()),
                ('document_series', models.CharField(blank=True, max_length=10, null=True)),
                ('document_type_txt', models.CharField(max_length=20)),
                ('person_surname_txt', models.CharField(max_length=50)),
                ('person_name_txt', models.CharField(max_length=50)),
                ('person_father_name_txt', models.CharField(blank=True, max_length=50, null=True)),
                ('authority_no', models.CharField(blank=True, max_length=20, null=True)),
                ('valid_from_dt', models.DateTimeField()),
            ],
            options={
                'db_table': 'person_document',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonDocumentArchived',
            fields=[
                ('person_document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_no', models.IntegerField()),
                ('document_series', models.CharField(blank=True, max_length=10, null=True)),
                ('document_type_txt', models.CharField(max_length=20)),
                ('person_surname_txt', models.CharField(max_length=50)),
                ('person_name_txt', models.CharField(max_length=50)),
                ('person_father_name_txt', models.CharField(max_length=50)),
                ('authority_no', models.CharField(blank=True, max_length=20, null=True)),
                ('valid_from_dttm', models.DateTimeField()),
                ('valid_to_dttm', models.DateTimeField()),
            ],
            options={
                'db_table': 'person_document_archived',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_txt', models.CharField(max_length=100)),
                ('valid_from_dttm', models.DateTimeField()),
            ],
            options={
                'db_table': 'person_email',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonHomeAddress',
            fields=[
                ('person_home_address_id', models.AutoField(primary_key=True, serialize=False)),
                ('region_cd', models.SmallIntegerField()),
                ('city_txt', models.CharField(max_length=50)),
                ('street_txt', models.CharField(max_length=50)),
                ('house_txt', models.CharField(max_length=10)),
                ('flat_nm', models.SmallIntegerField(blank=True, null=True)),
                ('valid_from_dttm', models.DateTimeField()),
            ],
            options={
                'db_table': 'person_home_address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonHomeAddressArchived',
            fields=[
                ('person_home_address_id', models.AutoField(primary_key=True, serialize=False)),
                ('region_cd', models.SmallIntegerField()),
                ('city_txt', models.CharField(max_length=50)),
                ('street_txt', models.CharField(max_length=50)),
                ('house_txt', models.CharField(max_length=10)),
                ('flat_nm', models.SmallIntegerField(blank=True, null=True)),
                ('valid_from_dttm', models.DateTimeField()),
                ('valid_to_dttm', models.DateTimeField()),
            ],
            options={
                'db_table': 'person_home_address_archived',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=20)),
                ('valid_from_dttm', models.DateTimeField()),
            ],
            options={
                'db_table': 'person_phone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContractTermination',
            fields=[
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cspcapp.Contract')),
                ('termination_dt', models.DateField(blank=True, null=True)),
                ('termination_reason_txt', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'contract_termination',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonXPerson',
            fields=[
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='person', serialize=False, to='cspcapp.Person')),
                ('connection_type_txt', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'person_x_person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentPerson',
            fields=[
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cspcapp.Person')),
                ('education_start_year', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student_person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentSchoolInfo',
            fields=[
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cspcapp.Person')),
                ('education_start', models.DateField(blank=True, null=True)),
                ('school_name_txt', models.CharField(blank=True, max_length=50, null=True)),
                ('education_end', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student_school_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentsOverviewView',
            fields=[
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cspcapp.Person')),
                ('person_surname_txt', models.CharField(max_length=50)),
                ('person_name_txt', models.CharField(max_length=50)),
                ('person_father_name_txt', models.CharField(blank=True, max_length=50, null=True)),
                ('school_name_txt', models.CharField(blank=True, max_length=50, null=True)),
                ('grade', models.SmallIntegerField()),
                ('liter', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'students_overview_view',
                'managed': False,
            },
        ),
    ]
