# Generated by Django 2.2.1 on 2019-07-05 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cspcapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContractOverviewByPerson',
        ),
        migrations.DeleteModel(
            name='PersonDocumentArchived',
        ),
        migrations.DeleteModel(
            name='PersonHomeAddressArchived',
        ),
        migrations.DeleteModel(
            name='StudentsOverviewView',
        ),
    ]
