# Generated by Django 2.2.1 on 2019-07-05 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cspcapp', '0002_auto_20190705_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractOverviewByPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.IntegerField()),
                ('contract_dt', models.DateField()),
                ('person_id', models.IntegerField()),
                ('document_series', models.CharField(blank=True, max_length=10, null=True)),
                ('document_no', models.IntegerField()),
                ('person_surname_txt', models.CharField(max_length=50)),
                ('person_name_txt', models.CharField(max_length=50)),
                ('person_father_name_txt', models.CharField(blank=True, max_length=50, null=True)),
                ('connection_type_txt', models.CharField(max_length=50)),
                ('course_id', models.IntegerField()),
                ('sphere_txt', models.CharField(blank=True, max_length=100, null=True)),
                ('name_txt', models.CharField(max_length=100)),
                ('number_of_payments', models.BigIntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentsOverviewView',
            fields=[
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cspcapp.Person')),
                ('person_surname_txt', models.CharField(max_length=50)),
                ('person_name_txt', models.CharField(max_length=50)),
                ('person_father_name_txt', models.CharField(blank=True, max_length=50, null=True)),
                ('school_name_txt', models.CharField(blank=True, max_length=50, null=True)),
                ('grade', models.SmallIntegerField()),
                ('liter', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'students_overview_view',
                'managed': False,
            },
        ),
    ]
